server:
  port: 8090
  path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://foodtrucks.cxuvoqdobozt.us-east-1.rds.amazonaws.com:3306/foodtrucks?serverTimezone=GMT%2b8
    username: root
    password: 2*&^wer123AsD  # For the convenience of testing, the database configuration is temporarily placed here, usually encrypted or placed in the configuration center

mybatis:
  mapper-locations: mapper/*Dao.xml
