server:
  port: 8090
  path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxxx:3306/foodtrucks?serverTimezone=GMT%2b8
    username: xxxxxx
    password: xxxxxx

mybatis:
  mapper-locations: mapper/*Dao.xml